# Auto-generated page element selectors
# Generated on: 2025-04-03 12:28:29

# Interactive elements
A_0 = '.header-logo'  # a: 自然人电子税务局
DIV_1 = '.header-title'  # div: 自然人电子税务局
DIV_2 = '.header-message-bar.el-popover__reference'  # div: 8
手机APP = '.show-download-app.el-popover__reference'  # a: 手机APP
帮助中心 = 'div > a:nth-child(3)'  # a: 帮助中心
下载服务 = 'div > a:nth-child(5)'  # a: 下载服务
电子税务局 = 'div > a:nth-child(7)'  # a: 电子税务局
A_7 = '.pending-tasks-info'  # a: 待办 0
EL_8 = '.badge-msg'  # sup: 8
SPAN_9 = '.header-user-thumb.el-popover__reference'  # span: 
INPUT_10 = '.header-search-input.el-popover__reference'  # input: 
A_11 = '.message-info'  # a: 8
SPAN_12 = '.badge'  # span: 8
I_13 = '.icon.icon-message'  # i: 
自然人电子税务局 = 'div > span:nth-child(1)'  # span: 自然人电子税务局
待办 = '.badge'  # a: 待办 0
首页 = '.navbar-first-menu'  # a: 首页
我要办税 = '.navbar-first-menu'  # a: 我要办税
我要查询 = '.navbar-first-menu'  # a: 我要查询
公众服务 = '.navbar-first-menu'  # a: 公众服务
特色应用 = '.navbar-first-menu'  # a: 特色应用
完善个人信息 = '.el-button.el-button--primary.is-plain'  # a: 完善个人信息
DIV_22 = '.customer-service-group.customer-service-list'  # div: 我要咨询
DIV_23 = '.customer-service-item'  # div: 我要咨询
点击查看 = '.notice-carousel-link'  # a: 点击查看
DIV_25 = '.customer-service-icon'  # div: 
点击查看_1 = '.notice-carousel-link'  # a: 点击查看
DIV_27 = '.customer-service-text'  # div: 我要咨询
我要咨询 = 'div > span'  # span: 我要咨询
点击查看_2 = '.notice-carousel-link'  # a: 点击查看
点击查看_3 = '.notice-carousel-link'  # a: 点击查看
LI_31 = '.common-business-item'  # li: 年度汇算（仅取得境内综合所得适用） 居民个人综合所得年度汇算
LI_32 = '.common-business-item'  # li: 年度汇算（取得境外所得适用） 居民个人综合所得年度汇算申报（
LI_33 = '.common-business-item'  # li: 专项附加扣除填报 子女教育、继续教育等专项附加扣除的填报
LI_34 = '.common-business-item.common-business-item-last'  # li: 经营所得（A表） 生产经营及承包承租经营所得月度或者季度预缴
IMG_35 = 'li > img'  # img: 
IMG_36 = 'li > img'  # img: 
IMG_37 = 'li > img'  # img: 
IMG_38 = 'li > img'  # img: 
年度汇算_仅取得境内综合所得适用 = '.common-business-title'  # p: 年度汇算（仅取得境内综合所得适用）
年度汇算_取得境外所得适用 = '.common-business-title'  # p: 年度汇算（取得境外所得适用）
专项附加扣除填报 = '.common-business-title'  # p: 专项附加扣除填报
经营所得_A表 = '.common-business-title'  # p: 经营所得（A表）
子女教育_继续教育等专项附加扣除的填报 = '.common-business-text'  # span: 子女教育、继续教育等专项附加扣除的填报
生产经营及承包承租经营所得月度或者季度预缴申报 = '.common-business-text'  # span: 生产经营及承包承租经营所得月度或者季度预缴申报
居民个人综合所得年度汇算申报_仅取得境内综合所得适用 = '.common-business-text'  # span: 居民个人综合所得年度汇算申报（仅取得境内综合所得适用）
居民个人综合所得年度汇算申报_取得境外所得适用 = '.common-business-text'  # span: 居民个人综合所得年度汇算申报（取得境外所得适用）
LI_47 = '.common-business-item'  # li: 经营所得（B表） 生产经营及承包承租经营所得的年度汇缴申报
LI_48 = '.common-business-item'  # li: 纳税记录开具 已缴款记录的在线查询、下载和打印
LI_49 = '.common-business-item'  # li: 专项附加扣除信息查询 已填报的各项专项附加扣除记录的查询
LI_50 = '.common-business-item.common-business-item-last'  # li: 申报查询 已完成申报的申报表查询
IMG_51 = 'li > img'  # img: 
IMG_52 = 'li > img'  # img: 
IMG_53 = 'li > img'  # img: 
IMG_54 = 'li > img'  # img: 
经营所得_B表 = '.common-business-title'  # p: 经营所得（B表）
纳税记录开具 = '.common-business-title'  # p: 纳税记录开具
专项附加扣除信息查询 = '.common-business-title'  # p: 专项附加扣除信息查询
申报查询 = '.common-business-title'  # p: 申报查询
生产经营及承包承租经营所得的年度汇缴申报 = '.common-business-text'  # span: 生产经营及承包承租经营所得的年度汇缴申报
已缴款记录的在线查询_下载和打印 = '.common-business-text'  # span: 已缴款记录的在线查询、下载和打印
已填报的各项专项附加扣除记录的查询 = '.common-business-text'  # span: 已填报的各项专项附加扣除记录的查询
已完成申报的申报表查询 = '.common-business-text'  # span: 已完成申报的申报表查询
热点问题 = 'div > a'  # a: 热点问题
查看更多 = 'li > a'  # a: 查看更多
I_65 = '.iconfont.icon-enter'  # i: 
税收政策及解读 = 'div > a'  # a: 税收政策及解读
通知公告 = 'div > a'  # a: 通知公告
查看更多_1 = 'li > a'  # a: 查看更多
查看更多_2 = 'li > a'  # a: 查看更多
I_70 = '.iconfont.icon-enter'  # i: 
I_71 = '.iconfont.icon-enter'  # i: 
平台功能简介 = 'span > a'  # a: 平台功能简介
平台服务 = 'span > a'  # a: 平台服务
用户注册 = 'span > a'  # a: 用户注册
用户登录 = 'span > a'  # a: 用户登录
找回密码 = 'span > a'  # a: 找回密码
子女教育支出 = 'span > a'  # a: 子女教育支出
继续教育支出 = 'span > a'  # a: 继续教育支出
大病医疗支出 = 'span > a'  # a: 大病医疗支出
住房贷款利息支出 = 'span > a'  # a: 住房贷款利息支出
住房租金支出 = 'span > a'  # a: 住房租金支出
赡养老人支出 = 'span > a'  # a: 赡养老人支出
EL_3岁以下婴幼儿照护支出 = 'span > a'  # a: 3岁以下婴幼儿照护支出
LI_84 = '.footer-map-item'  # li: 我要办税 专项附加扣除填报 税费申报 证明开具
我要办税_1 = '.footer-map-title'  # a: 我要办税
LI_86 = '.footer-map-item'  # li: 我要查询 申报信息查询 备案信息查询 其他查询
我要查询_1 = '.footer-map-title'  # a: 我要查询
LI_88 = '.footer-map-item'  # li: 公众服务 票证查验 帮助中心
公众服务_1 = '.footer-map-title'  # a: 公众服务
LI_90 = '.footer-map-item'  # li: 特色应用
特色应用_1 = '.footer-map-title'  # a: 特色应用
专项附加扣除填报_1 = '.footer-map-link'  # a: 专项附加扣除填报
申报信息查询 = '.footer-map-link'  # a: 申报信息查询
票证查验 = '.footer-map-link'  # a: 票证查验
税费申报 = '.footer-map-link'  # a: 税费申报
备案信息查询 = '.footer-map-link'  # a: 备案信息查询
帮助中心_1 = '.footer-map-link'  # a: 帮助中心
我的委托 = '.footer-map-link'  # a: 我的委托
其他查询 = '.footer-map-link'  # a: 其他查询
A_100 = '.footer-gov-img'  # a: 
IMG_101 = 'a > img'  # img: 
A_102 = '.footer-seek-error-img'  # a: 
IMG_103 = 'a > img'  # img: 
网站声明 = '.footer-copyright-link'  # a: 网站声明
京ICP备13021685号_2 = '.footer-copyright-link'  # a: 京ICP备13021685号-2
个人信息及隐私保护政策 = '.footer-copyright-link'  # a: 个人信息及隐私保护政策
京公网安备_11040102700073号 = '.footer-copyright-link'  # a: 京公网安备 11040102700073号
IMG_108 = 'a > img'  # img: 

# Form elements
