# Auto-generated page element selectors
# Generated on: 2025-03-10 19:53:24

# Interactive elements
SKIP_TO_CONTENT = '.p-3.color-bg-accent-emphasis.color-fg-on-emphasis.show-on-focus.js-skip-to-content'  # a: Skip to content
DIALOG_SHOW_DIALOG_B9883D2B_AA50_4748_BD = '#dialog-show-dialog-b9883d2b-aa50-4748-bd8f-6df92d50ed9a'  # button: 
A_2 = '.AppHeader-logo.ml-1'  # a: 
A_3 = '.AppHeader-context-item'  # a: ew384
A_4 = '.AppHeader-context-item'  # a: intelligent_agent
BUTTON_5 = '.AppHeader-searchButton.form-control.input-contrast.text-left.color-fg-subtle.no-wrap.placeholder'  # button: Type / to search
COPILOT_CHAT_HEADER_BUTTON = '#copilot-chat-header-button'  # button: 
GLOBAL_COPILOT_MENU_BUTTON = '#global-copilot-menu-button'  # button: 
GLOBAL_CREATE_MENU_ANCHOR = '#global-create-menu-anchor'  # button: 
ICON_BUTTON_23ED9C68_3AFF_4095_B72E_D72D = '#icon-button-23ed9c68-3aff-4095-b72e-d72de55be604'  # a: 
ICON_BUTTON_1E51E2AA_CEEE_4FCD_8423_D4C3 = '#icon-button-1e51e2aa-ceee-4fcd-8423-d4c39bb314b1'  # a: 
APPHEADER_NOTIFICATIONS_BUTTON = '#AppHeader-notifications-button'  # a: 
BUTTON_12 = '.Button--invisible.Button--medium.Button.Button--invisible-noVisuals.color-bg-transparent.p-0'  # button: 
SPAN_13 = '.Button-content'  # span: 
SPAN_14 = '.Button-label'  # span: 
IMG_15 = '.avatar.circle'  # img: 
EW384 = '.AppHeader-context-item-label'  # span: ew384
INTELLIGENT_AGENT = '.AppHeader-context-item-label'  # span: intelligent_agent
DIV_18 = '.overflow-hidden'  # div: Type / to search
SPAN_19 = '.Button-content'  # span: 
SPAN_20 = '.Button-label'  # span: 
LABEL_21 = '.AppHeader-search-visual--leading'  # label: 
QB_INPUT_QUERY = '#qb-input-query'  # span: Type / to search
SPAN_23 = '.Button-visual.Button-leadingVisual'  # span: 
KBD_24 = '.AppHeader-search-kbd'  # kbd: /
CODE_TAB = '#code-tab'  # a: Code
CODE = 'a > span:nth-child(2)'  # span: Code
ISSUES_TAB = '#issues-tab'  # a: Issues 0
ISSUES = 'a > span:nth-child(2)'  # span: Issues
PULL_REQUESTS_TAB = '#pull-requests-tab'  # a: Pull requests 0
PULL_REQUESTS = 'a > span:nth-child(2)'  # span: Pull requests
ACTIONS_TAB = '#actions-tab'  # a: Actions
ACTIONS = 'a > span:nth-child(2)'  # span: Actions
PROJECTS_TAB = '#projects-tab'  # a: Projects 0
PROJECTS = 'a > span:nth-child(2)'  # span: Projects
SECURITY_TAB = '#security-tab'  # a: Security 22
SECURITY = 'a > span:nth-child(2)'  # span: Security
INSIGHTS_TAB = '#insights-tab'  # a: Insights
INSIGHTS = 'a > span:nth-child(2)'  # span: Insights
SETTINGS_TAB = '#settings-tab'  # a: Settings
SETTINGS = 'a > span:nth-child(2)'  # span: Settings
EL_22 = '.Counter'  # span: 22
INTELLIGENT_AGENT_1 = '.d-block.overflow-x-hidden.color-fg-default'  # a: intelligent_agent
RO = '#:ro:'  # button: Unwatch1
FORK_BUTTON = '#fork-button'  # button: Fork 0 Cannot fork because you
SUMMARY_45 = '.btn-sm.btn.BtnGroup-item.px-2.float-none'  # summary: 
BUTTON_46 = '.js-toggler-target.rounded-left-2.btn-with-aria-count.btn-sm.btn.BtnGroup-item'  # button: Star 0
SUMMARY_47 = '.btn-sm.btn.BtnGroup-item.px-2.float-none'  # summary: 
SPAN_48 = '.Box-sc-g0xbh4-0.gUkoLg.prc-Button-ButtonContent-HKbr-'  # span: Unwatch1
UNWATCH = '.prc-Button-Label-pTQ3x'  # span: Unwatch1
EL_1 = '.ml-2.Counter.rounded-3.NotificationsSubscriptionsMenu-module__watchCounter--nAbhU'  # span: 1
REPO_STARS_COUNTER_STAR = '#repo-stars-counter-star'  # span: 0
SPAN_52 = '.prc-Button-Visual-2epfX.prc-Button-VisualWrap-Db-eB'  # span: 
SPAN_53 = '.prc-Button-Visual-2epfX.prc-Button-VisualWrap-Db-eB'  # span: 
STAR = '.d-inline'  # span: Star
BRANCH_PICKER_REPOS_HEADER_REF_SELECTOR = '#branch-picker-repos-header-ref-selector'  # button: main
A_56 = '.Box-sc-g0xbh4-0.lmSMZJ.prc-Button-ButtonBase-c50BI'  # a: 1 Branch
A_57 = '.Box-sc-g0xbh4-0.lmSMZJ.prc-Button-ButtonBase-c50BI'  # a: 1 Tag
R5B5AB = '#:R5b5ab:'  # button: Add file
R55AB = '#:R55ab:'  # button: Code
GO_TO_FILE = '.prc-components-Input-Ic-y8'  # input: 
SUMMARY_61 = '.float-right'  # summary: 
DIV_62 = '.Link--secondary.pt-1.pl-2'  # div: 
SPAN_63 = '.Box-sc-g0xbh4-0.gUkoLg.prc-Button-ButtonContent-HKbr-'  # span: main
SPAN_64 = '.prc-Button-Label-pTQ3x'  # span: main
DIV_65 = '.Box-sc-g0xbh4-0.bZBlpz'  # div: main
DIV_66 = '.Box-sc-g0xbh4-0.lhTYNA'  # div: 
DIV_67 = '.Box-sc-g0xbh4-0.ffLUq.ref-selector-button-text-container'  # div: main
SPAN_68 = '.Box-sc-g0xbh4-0.gUkoLg.prc-Button-ButtonContent-HKbr-'  # span: 1 Branch
SPAN_69 = '.prc-Button-Label-pTQ3x'  # span: 1 Branch
SPAN_70 = '.Box-sc-g0xbh4-0.gUkoLg.prc-Button-ButtonContent-HKbr-'  # span: 1 Tag
SPAN_71 = '.prc-Button-Label-pTQ3x'  # span: 1 Tag
SPAN_72 = '.prc-Button-ButtonContent-HKbr-'  # span: Add file
ADD_FILE = '.prc-Button-Label-pTQ3x'  # span: Add file
SPAN_74 = '.prc-Button-ButtonContent-HKbr-'  # span: Code
CODE_1 = '.prc-Button-Label-pTQ3x'  # span: Code
MAIN = '.Box-sc-g0xbh4-0.bmcJak.prc-Text-Text-0ima0'  # span: main
SPAN_77 = '.prc-Button-Visual-2epfX.prc-Button-VisualWrap-Db-eB'  # span: 
SPAN_78 = '.prc-Button-Visual-2epfX.prc-Button-VisualWrap-Db-eB'  # span: 
BRANCH = 'span > span'  # span: 1 Branch
EL_1_1 = '.color-fg-default'  # strong: 1
SPAN_81 = '.prc-Button-Visual-2epfX.prc-Button-VisualWrap-Db-eB'  # span: 
TAG = 'span > span'  # span: 1 Tag
EL_1_2 = '.color-fg-default'  # strong: 1
SPAN_84 = '.prc-Button-Visual-2epfX.prc-Button-VisualWrap-Db-eB'  # span: 
SPAN_85 = '.prc-Button-Visual-2epfX.prc-Button-VisualWrap-Db-eB'  # span: 
SPAN_86 = '.prc-Button-Visual-2epfX.prc-Button-VisualWrap-Db-eB'  # span: 
A_87 = '.prc-Button-ButtonBase-c50BI.d-none.d-lg-flex.LinkButton-module__code-view-link-button--xvCGA.flex-items-center.fgColor-default'  # a: 42 Commits
A_88 = '.prc-Link-Link-85e08'  # a: 
IMG_89 = '.Box-sc-g0xbh4-0.cvdqJW.prc-Avatar-Avatar-ZRS-m'  # img: 
EW384_1 = '.Box-sc-g0xbh4-0.dkaFxu.prc-Link-Link-85e08'  # a: ew384
SPAN_91 = '.prc-Button-ButtonContent-HKbr-'  # span: 42 Commits
SPAN_92 = '.prc-Button-Label-pTQ3x'  # span: 42 Commits
EL_515A4E6 = '.Link--secondary.prc-Link-Link-85e08'  # a: 515a4e6
REMOVE_BROWSER_TEST_FOLDER_FROM_REPOSITO = '.Link--secondary'  # a: Remove browser_test folder fro
SPAN_95 = '.prc-Button-Visual-2epfX.prc-Button-VisualWrap-Db-eB'  # span: 
EL_42_COMMITS = '.fgColor-default'  # span: 42 Commits
README = '.Link--muted'  # a: Readme
API_GATEWAY = '.Link--primary'  # a: api_gateway
REMOVE__DS_STORE_FILES = '.Link--secondary'  # a: Remove .DS_Store files
A_100 = '.Link.Link--muted'  # a: Activity
ACTIVITY = '.color-fg-muted'  # span: Activity
COMMON = '.Link--primary'  # a: common
REMOVE___PYCACHE___FOLDERS_FROM_REPOSITO = '.Link--secondary'  # a: Remove __pycache__ folders fro
STARS = '.Link.Link--muted'  # a: 0 stars
EL_0 = 'a > strong'  # strong: 0
ORCHESTRATOR_SERVICE = '.Link--primary'  # a: orchestrator_service
FEAT__ADD_WECHAT_TOOL_FUNCTIONALITY = '.Link--secondary'  # a: feat: add wechat tool function
WATCHING = '.Link.Link--muted'  # a: 1 watching
EL_1_3 = 'a > strong'  # strong: 1
FORKS = '.Link.Link--muted'  # a: 0 forks
EL_0_1 = 'a > strong'  # strong: 0
PAGE_ANALYZER = '.Link--primary'  # a: page_analyzer
PAGE_ANALYZER_AUTOMATION = '.Link--secondary'  # a: page analyzer automation
SCENARIO_SERVICE = '.Link--primary'  # a: scenario_service
FEAT__ADD_WECHAT_TOOL_FUNCTIONALITY_1 = '.Link--secondary'  # a: feat: add wechat tool function
RELEASES = '.Link--primary.no-underline.Link'  # a: Releases
TESTS = '.Link--primary'  # a: tests
REMOVE_BROWSER_TEST_FOLDER_FROM_REPOSITO_1 = '.Link--secondary'  # a: Remove browser_test folder fro
A_119 = '.Link--primary.no-underline'  # a: 1 tags
EL_1_4 = '.text-bold'  # span: 1
TAGS = '.color-fg-muted'  # span: tags
CREATE_A_NEW_RELEASE = '.Link--inTextBlock'  # a: Create a new release
TOOL_SERVICE = '.Link--primary'  # a: tool_service
FIX_GET_OR_CREATE_TAB = '.Link--secondary'  # a: fix get_or_create_tab
GITIGNORE = '.Link--primary'  # a: .gitignore
REMOTE_BROWSER_TEST = '.Link--secondary'  # a: remote browser_test
PACKAGES = '.Link--primary.no-underline.Link.d-flex.flex-items-center'  # a: Packages 0
MAKEFILE = '.Link--primary'  # a: Makefile
INIT_COMMIT = '.Link--secondary'  # a: init commit
PUBLISH_YOUR_FIRST_PACKAGE = '.Link--inTextBlock'  # a: Publish your first package
README_MD = '.Link--primary'  # a: README.md
FIX_BASE = '.Link--secondary'  # a: fix base
INIT___PY = '.Link--primary'  # a: __init__.py
UDPATE = '.Link--secondary'  # a: udpate
APP_PY = '.Link--primary'  # a: app.py
FIX_GET_OR_CREATE_TAB_1 = '.Link--secondary'  # a: fix get_or_create_tab
A_137 = '.d-inline-flex.flex-items-center.flex-nowrap.Link--secondary.no-underline.text-small.mr-3'  # a: Python 80.7%
PYTHON = '.color-fg-default.text-bold.mr-1'  # span: Python
EL_80_7 = 'a > span:nth-child(3)'  # span: 80.7%
A_140 = '.d-inline-flex.flex-items-center.flex-nowrap.Link--secondary.no-underline.text-small.mr-3'  # a: Jupyter Notebook 19.3%
JUPYTER_NOTEBOOK = '.color-fg-default.text-bold.mr-1'  # span: Jupyter Notebook
EL_19_3 = 'a > span:nth-child(3)'  # span: 19.3%
BROWSER_CONFIG_JSON = '.Link--primary'  # a: browser_config.json
USE_CHROME_DRIVER = '.Link--secondary'  # a: use chrome driver
DOCKER_COMPOSE_YML = '.Link--primary'  # a: docker-compose.yml
INIT_COMMIT_1 = '.Link--secondary'  # a: init commit
LOGGING_CONF = '.Link--primary'  # a: logging.conf
UPDATE_TESTS = '.Link--secondary'  # a: update tests
A_149 = '.Button--secondary.Button--small.Button.ml-auto'  # a: Configure Python package
REQUIREMENTS_TXT = '.Link--primary'  # a: requirements.txt
UPDATE_REQUIREMENTS_TXT = '.Link--secondary'  # a: update requirements.txt
SPAN_152 = '.Button-content'  # span: Configure Python package
CONFIGURE = '.Button-label'  # span: Configure Python package
PYTHON_PACKAGE = '.sr-only'  # span: Python package
RUN_APP_SH = '.Link--primary'  # a: run_app.sh
ADD_STREAMLIT_APP = '.Link--secondary'  # a: add streamlit app
RUN_LOCAL_PY = '.Link--primary'  # a: run_local.py
FEAT__ADD_WECHAT_TOOL_FUNCTIONALITY_2 = '.Link--secondary'  # a: feat: add wechat tool function
A_159 = '.Button--secondary.Button--small.Button.ml-auto'  # a: Configure Python Package using
SPAN_160 = '.Button-content'  # span: Configure Python Package using
CONFIGURE_1 = '.Button-label'  # span: Configure Python Package using
PYTHON_PACKAGE_USING_ANACONDA = '.sr-only'  # span: Python Package using Anaconda
SCENARIO_TEST_PY = '.Link--primary'  # a: scenario-test.py
PAGE_ANALYZER_AUTOMATION_1 = '.Link--secondary'  # a: page analyzer automation
A_165 = '.UnderlineTabbedInterface__StyledUnderlineItem-sc-4ilrg0-2.beOdPj'  # a: README
RR9AB = '#:Rr9ab:'  # button: 
EDIT_FILE = '.Box-sc-g0xbh4-0.ecwqhm.prc-Button-ButtonBase-c50BI.prc-Button-IconButton-szpyj'  # button: 
README_1 = 'a > span:nth-child(2)'  # span: README
SPAN_169 = 'a > span:nth-child(1)'  # span: 
INTELLIGENT_AGENT_2 = '.heading-element'  # h1: intelligent-agent
A_171 = '.Button--secondary.Button--small.Button.ml-auto'  # a: Configure Pylint
SPAN_172 = '.Button-content'  # span: Configure Pylint
CONFIGURE_2 = '.Button-label'  # span: Configure Pylint
PYLINT = '.sr-only'  # span: Pylint
AGENT系统使用说明 = '.heading-element'  # h1: Agent系统使用说明
MORE_WORKFLOWS = '.Link'  # a: More workflows
BUTTON_177 = '.Button--link.Button--medium.Button.text-small.color-fg-muted.text-normal'  # button: Dismiss suggestions
SPAN_178 = '.Button-content'  # span: Dismiss suggestions
DISMISS_SUGGESTIONS = '.Button-label'  # span: Dismiss suggestions
环境要求 = '.heading-element'  # h2: 环境要求
快速启动 = '.heading-element'  # h2: 快速启动
CLIPBOARD_COPY_182 = '.ClipboardButton.btn.btn-invisible.js-clipboard-copy.m-2.p-0.d-flex.flex-justify-center.flex-items-center'  # clipboard-copy: 
CLIPBOARD_COPY_183 = '.ClipboardButton.btn.btn-invisible.js-clipboard-copy.m-2.p-0.d-flex.flex-justify-center.flex-items-center'  # clipboard-copy: 
CLIPBOARD_COPY_184 = '.ClipboardButton.btn.btn-invisible.js-clipboard-copy.m-2.p-0.d-flex.flex-justify-center.flex-items-center'  # clipboard-copy: 
测试场景 = '.heading-element'  # h2: 测试场景
信用卡账单查询 = '.heading-element'  # h3: 信用卡账单查询
CLIPBOARD_COPY_187 = '.ClipboardButton.btn.btn-invisible.js-clipboard-copy.m-2.p-0.d-flex.flex-justify-center.flex-items-center'  # clipboard-copy: 
简历筛选与评估 = '.heading-element'  # h3: 简历筛选与评估
CLIPBOARD_COPY_189 = '.ClipboardButton.btn.btn-invisible.js-clipboard-copy.m-2.p-0.d-flex.flex-justify-center.flex-items-center'  # clipboard-copy: 
电商平台运营 = '.heading-element'  # h3: 电商平台运营
CLIPBOARD_COPY_191 = '.ClipboardButton.btn.btn-invisible.js-clipboard-copy.m-2.p-0.d-flex.flex-justify-center.flex-items-center'  # clipboard-copy: 
价格比较与购物车 = '.heading-element'  # h3: 价格比较与购物车
CLIPBOARD_COPY_193 = '.ClipboardButton.btn.btn-invisible.js-clipboard-copy.m-2.p-0.d-flex.flex-justify-center.flex-items-center'  # clipboard-copy: 
服务访问端口 = '.heading-element'  # h2: 服务访问端口
HTTP___LOCALHOST_8000 = 'li > a'  # a: http://localhost:8000
HTTP___LOCALHOST_8001 = 'li > a'  # a: http://localhost:8001
HTTP___LOCALHOST_8002 = 'li > a'  # a: http://localhost:8002
HTTP___LOCALHOST_8003 = 'li > a'  # a: http://localhost:8003
自定义场景 = '.heading-element'  # h2: 自定义场景
项目结构 = '.heading-element'  # h2: 项目结构
CLIPBOARD_COPY_201 = '.ClipboardButton.btn.btn-invisible.js-clipboard-copy.m-2.p-0.d-flex.flex-justify-center.flex-items-center'  # clipboard-copy: 
注意事项 = '.heading-element'  # h2: 注意事项
项目结构_1 = '.heading-element'  # h2: 项目结构
CLIPBOARD_COPY_204 = '.ClipboardButton.btn.btn-invisible.js-clipboard-copy.m-2.p-0.d-flex.flex-justify-center.flex-items-center'  # clipboard-copy: 
GITHUB = '.footer-octicon.mr-2'  # a: 
MANAGE_COOKIES = '.Link--secondary.underline-on-hover.border-0.p-0.color-bg-transparent'  # button: Manage cookies
DO_NOT_SHARE_MY_PERSONAL_INFORMATION = '.Link--secondary.underline-on-hover.border-0.p-0.color-bg-transparent'  # button: Do not share my personal infor
TERMS = '.Link--secondary.Link'  # a: Terms
PRIVACY = '.Link--secondary.Link'  # a: Privacy
SECURITY_1 = '.Link--secondary.Link'  # a: Security
STATUS = '.Link--secondary.Link'  # a: Status
DOCS = '.Link--secondary.Link'  # a: Docs
CONTACT = '.Link--secondary.Link'  # a: Contact

# Form elements
FORM_FORM_0 = '.js-social-form.BtnGroup-parent.flex-auto'  # form: 
FORM_FORM_1 = '.js-notice-dismiss'  # form: 
